const fs = require('fs');
const path = 'model.ipynb';
const notebook = JSON.parse(fs.readFileSync(path, 'utf8'));
const add = (cell_type, source) => notebook.cells.push({cell_type, execution_count:null, metadata:{}, outputs:[], source:source.split('\\n').map((x,i,a)=>x+(i<a.length-1?'\\n':''))});
add('markdown', '# Stage 2 - voter turnout target\\n\\nWe are focusing on turnout first. The root IEC baseline is the canonical outcome source. Provincial workbooks remain separate until overlap and completeness are reconciled.\\n\\nThe modelling grain is one row per municipality x election year x ballot type. We remove repeated party rows before aggregation.');
add('code', `# Select outcome fields from the root IEC baseline.\\nturnout_fields = [\\n    'election_year', 'province', 'municipality_code', 'municipality_source',\\n    'ward_code', 'voting_district', 'station_name', 'registered_voters',\\n    'ballot_type', 'ballot_votes_cast', 'spoilt_votes', 'party_valid_votes_sum',\\n    'reported_turnout_pct', 'source_filename'\\n]\\nturnout_raw = pd.read_csv(BASELINE_PATH, usecols=turnout_fields, low_memory=False)\\nprint(f'turnout_raw shape: {turnout_raw.shape}')\\ndisplay(turnout_raw.head(3))`);
add('code', `# Party rows repeat reporting-unit measures. Keep one row per reporting unit and ballot.\\nreporting_unit_cols = [\\n    'source_filename', 'election_year', 'province', 'municipality_code',\\n    'municipality_source', 'ward_code', 'voting_district', 'station_name',\\n    'registered_voters', 'ballot_type'\\n]\\nmetric_cols = ['ballot_votes_cast', 'spoilt_votes', 'party_valid_votes_sum', 'reported_turnout_pct']\\nunit_conflicts = (\\n    turnout_raw.groupby(reporting_unit_cols, dropna=False)[metric_cols]\\n    .nunique(dropna=False)\\n    .reset_index()\\n)\\nfor col in metric_cols:\\n    unit_conflicts[f'{col}_conflict'] = unit_conflicts[col] > 1\\nconflict_flags = [f'{col}_conflict' for col in metric_cols]\\nunit_conflicts['any_metric_conflict'] = unit_conflicts[conflict_flags].any(axis=1)\\nprint('Reporting units with conflicting repeated measures:', int(unit_conflicts['any_metric_conflict'].sum()))\\n\\nturnout_units = turnout_raw.drop_duplicates(reporting_unit_cols).copy()\\nprint(f'turnout_units shape: {turnout_units.shape}')`);
add('code', `# Aggregate to municipality x election year x ballot type.\\nmunicipality_turnout = (\\n    turnout_units.groupby(\\n        ['province', 'municipality_code', 'municipality_source', 'election_year', 'ballot_type'],\\n        dropna=False, as_index=False\\n    )\\n    .agg(\\n        registered_voters=('registered_voters', 'sum'),\\n        ballot_votes_cast=('ballot_votes_cast', 'sum'),\\n        spoilt_votes=('spoilt_votes', 'sum'),\\n        party_valid_votes_sum=('party_valid_votes_sum', 'sum'),\\n        reporting_units=('voting_district', 'size'),\\n        source_files=('source_filename', lambda s: '; '.join(sorted(set(s.dropna().astype(str)))))\\n    )\\n)\\nmunicipality_turnout['turnout_pct'] = (\\n    100 * municipality_turnout['ballot_votes_cast'] / municipality_turnout['registered_voters'].replace({0: np.nan})\\n)\\nmunicipality_turnout['spoilt_rate_pct'] = (\\n    100 * municipality_turnout['spoilt_votes'] / municipality_turnout['ballot_votes_cast'].replace({0: np.nan})\\n)\\nmunicipality_turnout['votes_exceed_registered'] = (\\n    municipality_turnout['ballot_votes_cast'] > municipality_turnout['registered_voters']\\n)\\n\\nassert municipality_turnout[['municipality_code','election_year','ballot_type']].duplicated().sum() == 0\\nassert municipality_turnout['registered_voters'].ge(0).all()\\nassert municipality_turnout['ballot_votes_cast'].ge(0).all()\\n\\nmunicipality_turnout.to_csv(PROJECT_ROOT / 'derived_municipality_turnout.csv', index=False)\\ndisplay(municipality_turnout.head())\\nprint(f'Final turnout table shape: {municipality_turnout.shape}')`);
add('code', `# Quick outcome coverage and quality summary.\\nturnout_summary = {\\n    'provinces': int(municipality_turnout['province'].nunique()),\\n    'municipalities': int(municipality_turnout['municipality_code'].nunique()),\\n    'election_years': sorted(municipality_turnout['election_year'].dropna().unique().tolist()),\\n    'ballot_types': sorted(municipality_turnout['ballot_type'].dropna().astype(str).unique().tolist()),\\n    'duplicate_target_keys': int(municipality_turnout[['municipality_code','election_year','ballot_type']].duplicated().sum()),\\n    'invalid_turnout_rows': int((~municipality_turnout['turnout_pct'].between(0, 100, inclusive='both')).sum()),\\n    'votes_exceed_registered_rows': int(municipality_turnout['votes_exceed_registered'].sum()),\\n}\\nturnout_summary`);
fs.writeFileSync(path, JSON.stringify(notebook, null, 1));
console.log('Appended Stage 2 turnout cells. Total cells:', notebook.cells.length);

