const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, Table, TableRow, TableCell, WidthType, BorderStyle, ShadingType, Footer, Header, VerticalAlign } = require('docx');
const fs = require('fs');

const OUT = 'DIRISA_2026_Data_Integration_Presentation_Brief.docx';
const navy = '16324F', teal = '0F766E', sky = 'E8F1F5', pale = 'F5F8FA', gold = 'B7791F', gray = '52606D', light = 'D9E2EC';
const borders = {top:{style:BorderStyle.SINGLE,size:4,color:light},bottom:{style:BorderStyle.SINGLE,size:4,color:light},left:{style:BorderStyle.SINGLE,size:4,color:light},right:{style:BorderStyle.SINGLE,size:4,color:light},insideHorizontal:{style:BorderStyle.SINGLE,size:4,color:light},insideVertical:{style:BorderStyle.SINGLE,size:4,color:light}};
function cell(text, opt={}) { return new TableCell({width:opt.width?{size:opt.width,type:WidthType.DXA}:undefined,shading:opt.shading?{fill:opt.shading,type:ShadingType.CLEAR}:undefined,margins:{top:100,bottom:100,left:130,right:130},verticalAlign:VerticalAlign.CENTER,children:[new Paragraph({spacing:{after:0},children:[new TextRun({text:String(text),font:'Aptos',size:opt.size||19,bold:!!opt.bold,color:opt.color||'1F2933'})]})]}); }
function table(headers, rows, widths) { return new Table({width:{size:9360,type:WidthType.DXA},borders,rows:[new TableRow({tableHeader:true,children:headers.map((x,i)=>cell(x,{bold:true,color:'FFFFFF',shading:navy,width:widths[i]}))}),...rows.map(r=>new TableRow({children:r.map((x,i)=>cell(x,{width:widths[i]}))}))]}); }
function h(text, level=1) { return new Paragraph({text,heading:level===1?HeadingLevel.HEADING_1:HeadingLevel.HEADING_2,keepNext:true,spacing:{before:level===1?260:170,after:90}}); }
function p(text,opt={}) { return new Paragraph({alignment:opt.align,spacing:{before:opt.before||0,after:opt.after===undefined?120:opt.after,line:opt.line||276},children:[new TextRun({text,font:'Aptos',size:opt.size||20,color:opt.color||'1F2933',bold:!!opt.bold,italics:!!opt.italics})]}); }
function bullet(text) { return new Paragraph({style:'List Bullet',spacing:{after:70,line:260},children:[new TextRun({text,font:'Aptos',size:19,color:'1F2933'})]}); }
function callout(label,text,color=teal) { return new Table({width:{size:9360,type:WidthType.DXA},borders:{top:{style:BorderStyle.SINGLE,size:8,color},bottom:{style:BorderStyle.SINGLE,size:8,color},left:{style:BorderStyle.SINGLE,size:24,color},right:{style:BorderStyle.SINGLE,size:8,color}},rows:[new TableRow({children:[new TableCell({shading:{fill:pale,type:ShadingType.CLEAR},margins:{top:150,bottom:150,left:220,right:180},children:[new Paragraph({spacing:{after:50},children:[new TextRun({text:label.toUpperCase(),font:'Aptos',size:17,bold:true,color})]}),new Paragraph({spacing:{after:0},children:[new TextRun({text,font:'Aptos',size:19,color:'1F2933'})]})]})]})]}); }

const doc = new Document({creator:'DIRISA 2026 Datathon Team',title:'DIRISA 2026 Data Integration Presentation Brief',subject:'Current data integration work and presentation narrative',styles:{default:{document:{run:{font:'Aptos',size:20,color:'1F2933'},paragraph:{spacing:{after:120,line:276}}}},paragraphStyles:[{id:'TitleCustom',name:'Title Custom',basedOn:'Normal',run:{font:'Aptos Display',size:38,bold:true,color:navy},paragraph:{spacing:{after:160,line:320}}},{id:'SubtitleCustom',name:'Subtitle Custom',basedOn:'Normal',run:{font:'Aptos',size:22,color:gray},paragraph:{spacing:{after:260,line:300}}},{id:'List Bullet',name:'List Bullet',basedOn:'Normal',paragraph:{indent:{left:420,hanging:220},spacing:{after:70,line:260}}}]},sections:[{properties:{page:{margin:{top:900,right:900,bottom:850,left:900}}},headers:{default:new Header({children:[new Paragraph({alignment:AlignmentType.RIGHT,children:[new TextRun({text:'DIRISA 2026 | Presentation Brief',font:'Aptos',size:15,color:gray})]})]})},footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:'Current status: source registration and raw ingestion complete; analytical joins pending validation',font:'Aptos',size:14,color:gray})]})]})},children:[]}]});
const C=doc.documentWrapper.document.body.root; C.length=0; C.push(new Paragraph({}));
C.push(new Paragraph({style:'TitleCustom',children:[new TextRun({text:'DIRISA 2026 Data Integration Presentation Brief'})]}));
C.push(new Paragraph({style:'SubtitleCustom',children:[new TextRun({text:'What we have integrated, how the sources relate, and what happens next'})]}));
C.push(p('Prepared for team discussion and datathon presentation | 23 September 2026',{size:17,color:gray,after:220}));
C.push(callout('Core message','We are building an auditable municipality-level evidence base by aligning historical IEC election outcomes, 2026 voter-registration information and Census context through a reviewed geography crosswalk. The sources are registered and imported; the final analytical joins are deliberately still pending validation.',teal));
C.push(h('1. One-minute presentation script'));
C.push(p('Our project investigates unequal electoral participation, with an initial focus on Mpumalanga municipalities. We are integrating three complementary sources. The IEC baseline provides historical election outcomes such as registered voters, votes cast, turnout and spoilt ballots. The 2026 voter-registration workbook provides current registration totals, including municipality and age-gender information. Census 2022 provides demographic, socioeconomic, service-access and internet-access context at household level.'));
C.push(p('The sources do not share a ready-made analytical structure, so we are integrating them through three controls: time, geography and grain. We preserve the election year and reference period, map locations to a canonical municipality code, and convert the data to one row per municipality per election year. The IEC party and ballot records will be aggregated before modelling, while Census records will be weighted using the supplied household weights.'));
C.push(p('At the current stage, our sources have been catalogued, quality-controlled at import and loaded into one reproducible notebook. We have not claimed a final join yet: municipality mappings, Census definitions and aggregation checks must be validated first. This gives us a defensible foundation for analysing registration gaps, turnout gaps and participation profiles.',{bold:true}));
C.push(h('2. What each source contributes'));
C.push(table(['Source','Contribution','Current status','How it will enter the analysis'],[
['IEC historical baseline','Historical registered voters, votes cast, turnout, spoilt ballots and election-result measures.','Imported as `baseline_raw`; retained in long format.','Aggregate to municipality x election year before descriptive analysis or modelling.'],
['2026 registered voters workbook','Current registration totals by province, age/gender summaries and Mpumalanga municipality totals.','Imported as `voters_report_raw`; report layout preserved.','Split into tidy tables, validate municipality codes and use as current registration context.'],
['Census 2022 household extract','Demographic, housing, service-access and internet-access indicators.','Imported as `census_raw`; coded values preserved.','Decode variables, aggregate with `HH_WGT` and produce municipality-level context indicators.'],
['Metadata and crosswalk','Source lineage, field definitions, quality notes and canonical geography mapping.','Created under `metadata/`; loaded before raw data.','Controls every join and blocks unresolved geography records from modelling.']],[2200,2600,2200,2360]));
C.push(h('3. Integration pipeline'));
C.push(table(['Stage','What happens','Evidence we can show'],[
['1. Register','Record source, date, scope, grain, limitations and ownership.','Source registry and data dictionary.'],
['2. Import','Load raw files without changing values; record checksums and file manifest.','Notebook input manifest and raw object shapes.'],
['3. Standardise','Parse fields, preserve repair flags and normalise identifiers.','Before/after schema and quality report.'],
['4. Harmonise geography','Resolve source municipality names/codes to canonical codes.','Crosswalk with provisional and unresolved rows clearly marked.'],
['5. Aggregate','Convert long election rows and weighted Census households to compatible municipality-level tables.','Reconciliation totals and aggregation tests.'],
['6. Join','Join only validated municipality-level tables with explicit reference periods.','Join match rates, unmatched records and duplicate-key checks.'],
['7. Analyse','Separate registration gaps, turnout gaps and contextual associations.','Certified modelling table, charts and limitations.']],[1500,4400,3460]));
C.push(h('4. The three integration controls'));
C.push(table(['Control','Question we enforce','Example risk prevented'],[
['Time','When was this value measured, and would it be known before the outcome being predicted?','Using post-election turnout as a predictor of turnout.'],
['Geography','Does this record map to the same municipality boundary and canonical code?','Joining a Census municipality to the wrong historical election geography.'],
['Grain','What does one row represent, and are rows independent?','Treating repeated party rows in the 721,327-row baseline as independent municipalities.']],[1600,4300,3460]));
C.push(callout('Important wording','Say “the sources have been prepared and imported for integration” rather than “the datasets are fully integrated.” The final join is only complete after geography, weighting, denominator and reconciliation checks pass.',gold));
C.push(h('5. Current status and next actions'));
C.push(table(['Complete now','Next to complete','Why it matters'],[
['Metadata registry and data dictionary','Split the Excel report into tidy tables','The workbook contains multiple logical tables on one sheet.'],
['Input manifest and checksums','Attach official URLs, codebooks and boundary versions','Lineage and definitions must be reproducible.'],
['Raw imports in `model.ipynb`','Extract distinct baseline municipality code/name pairs','The baseline covers multiple provinces and election periods.'],
['Initial geography crosswalk','Resolve provisional and unresolved municipality records, including MP314','A wrong join can invalidate every downstream result.'],
['Root IEC baseline linked to metadata','Aggregate Census households using `HH_WGT`','Unweighted household summaries would misrepresent municipality context.']],[3000,3400,2960]));
C.push(h('6. Questions we should be ready to answer'));
['Why not model directly on the 721,327 baseline rows? Because the rows are party/ballot/source records, so many turnout and registration values repeat. We first aggregate to the modelling grain.','How do you know the sources refer to the same place? We use a canonical municipality crosswalk and report unmatched, ambiguous and boundary-version cases.','How are Census households made comparable to election data? We use the household weight, aggregate to municipality level and preserve the denominator and codebook definitions.','Are you predicting the 2026 result? Only prospectively unless actual 2026 outcomes are available. Historical rolling backtests provide the honest validation design.','What can the analysis establish? Associations and participation patterns. It cannot establish that a particular socioeconomic factor caused turnout differences without a stronger causal design.'].forEach(b=>C.push(bullet(b)));
C.push(h('7. Closing statement'));
C.push(p('Our strength is not simply having many rows or many sources. It is that we are making the integration auditable: every value has a source, every join has a geography decision, every rate has a denominator, and every model feature has a time cutoff. That foundation lets us move from descriptive participation gaps to responsible modelling and decision support.'));

Packer.toBuffer(doc).then(buf=>fs.writeFileSync(OUT,buf));
